name: explore context
on: [ push, workflow_dispatch ]
jobs:
    context:
      runs-on: ubuntu-latest
      steps:
        - name: github object
          run: echo "${{ toJSON(github) }}"
    upload:
      needs: context
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: some files
            path: 1-lets-echo/
    download:
      needs: upload
      runs-on: ubuntu-latest
      steps:
        - name: download artifacts
          uses: actions/download-artifact@v4
          with:
            name: some files
        - name: list contents
          run: ls
        - name: deploy
          run: echo "Deploying..."
