name: explore context
on: [ push, workflow_dispatch ]
jobs:
    context:
        runs-on: ubuntu-latest
        steps:
          - name: github object
            run: echo "${{ toJSON(github.repository) }}"
          - name: upload artifacts
            uses: actions/upload-artifact@v4
            with:
              name: some files
              path: 1-lets-echo